services:
  - type: web
    name: econ3310-risk
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "otree prodserver $PORT"
    envVars:
      - key: OTREE_ADMIN_PASSWORD
        sync: false         # set in dashboard
      - key: OTREE_AUTH_LEVEL
        value: STUDY
      - key: OTREE_PRODUCTION
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: econ3310-db
          property: connectionString
databases:
  - name: econ3310-db
